### ISSUE TITLE
Business coercion

### ISSUE THREAD

**Issue by ghuntley** [ghuntley/covidsafe.watch#14]
https://twitter.com/bengrubb/status/1259695834809036800?s=19

**Comment by ghuntley** [comment]
https://twitter.com/PerisherResort/status/1259725400952864768?s=19

**Comment by ghuntley** [comment]
https://twitter.com/CocaColaAmatil/status/1257518972972367872?s=19

**Comment by yaakov-h** [comment]
McDonalds: https://twitter.com/mootpointer/status/1258670284007063552
Coles: https://twitter.com/halans/status/1258322382034366465

**Comment by ghuntley** [comment]
Qantas https://twitter.com/developerjack/status/1260334021864652801?s=19

**Comment by joshlama** [comment]
developerjack's tweet is gone

**Comment by joshlama** [comment]
See #18
